# Error Mitigation

This notebook contains theoretical background and examples for using our Error Mitigation module with Qiskit. 
We recommend to first read our [Quantum Detector Tomography Tutorial](QDT_Tutorial.ipynb).

## Theoretical background
Here we describe main theoretical concepts related to mitigation procedure. For more detailed description, see Ref. [0].

### Classical noise model

Let us denote by $\mathbf{M}$ a POVM describing noisy detector and $\mathbf{P}$ denote ideal measurement. In classical noise model, we assume that the relation between the two is given by stochastic, invertible map $\Lambda$:

$$ \mathbf{M} = \Lambda \mathbf{P}.$$

Let us denote by $\mathbf{p}_{exp}$ vector of probabilities obtained on a noisy detector $\mathbf{M}$ measuring any quantum state, and by $\mathbf{p_{ideal}}$ the analogous vector for ideal detector (for the same quantum state). From linearity of the Born's rule, it follows that two vectors are related by the same stochastic map as POVMs:

$$ \mathbf{p_{exp}} = \Lambda \mathbf{p_{ideal}}. $$

Recall that we assumed that $\Lambda$ is invertible. Hence by multiplying last equation by $\Lambda^{-1}$ from both sides, we obtain

$$ \Lambda^{-1} \mathbf{p_{exp}} = \mathbf{p_{ideal}}. $$

Effectively, by this kind of postprocessing, we obtain statistics which we would have obtained on the perfect detector devices.

### Deviations from noise model

There are several ways in which real noise can deviate from our model. Here we will show the way how to hanlde them.

#### Effects  on mitigation
Above we assumed a very specific noise model. In practice it is likely that it will not be fulfilled exactly. In such a scenario, we may perform the following decomposition of POVM $M$ describing our device:
$$ \mathbf{M} = \Lambda \mathbf{P} + \mathbf{\Delta}\ ,$$
where $\Delta$ denotes a "coherent" part of the noise and $\Lambda$, as previously, is some stochastic, invertible map. 

In such a case, we can relate probability vector obtained on the noisy detector to ideal one in manner similar as before

$$ \mathbf{p_{exp}} = \Lambda \mathbf{p_{ideal}} + \mathbf{d}\ , $$
where $\mathbf{d}$ denotes a disturbance of probability vector due to existence of coherent part of the noise.
If we now multiply the above expression by inverse of the noise matrix, we obtain

$$ \Lambda^{-1} \mathbf{p_{exp}} = \mathbf{p_{ideal}} + \Lambda^{-1} \mathbf{d}, \  $$


This clearly does not leave us with ideal statistics $\mathbf{p_{ideal}}$, but consists of additional deviation term $\Lambda^{-1} \mathbf{d}$ which appears due to non-classicity of noise. Fortunately, this does not preclude our mitigation from working! The correction clearly will not be perfect in this case, however if deviation is sufficiently small, it still might be better then performing no correction at all.

We can upper-bound the TV distance of corrected probability distribution from the ideal one by expression
$$
D_{TV}\left( \Lambda^{-1} \mathbf{p_{exp}},\mathbf{p_{ideal}} \right) \leq ||\Lambda^{-1}||_{1 \to 1} D_{op}(\mathbf{M}, \Lambda \mathbf{P}) \,
$$
where the $1\rightarrow 1$ norm is defined as
$$
||A||_{1\rightarrow1} = \sup_{||v||_1} ||Av||_1 \ .
$$

It is easy to see that if the detector $\mathbf{M}$ is related to $\mathbf{P}$ via only classical noise $\Lambda$, then the above expression yields $0$, hence the mitigation works perfectly.
In the presence of coherent measurement noise, term $D_{op}(\mathbf{M}, \Lambda \mathbf{P})$ may be regarded as a measure of non-classicity of the noise.

#### How to choose decomposition?

In general, we can always perform decomposition into "classical" and "coherent" part in infinitely many ways. However, for the ideal detector $P$ modeled as projective measurement in computational basis, there exists a perfectly natural ansatz. Namely, we propose to consider diagonal parts of POVM's $\mathbf{M}$ elements to describe classical part of the noise. 
As a justification for such choice, note that elements of $\mathbf{P}$ for such ideal detector model are diagonal, and the stochastic map would preserve the diagonality. 

Hence, after obtaining description of POVM $\mathbf{M}$ from detector tomography, reconstruction of $\Lambda$ can be achieved by taking only diagonal parts of POVM's elements.



### Finite-size statistics
#### Statistical noise
So far we have assumed that we have access to actual (noisy) probability distribution $\mathbf{p_{exp}}$. However, in real life what we can get is only an estimator of this distribution 

$$ \mathbf{p_{exp}} \xrightarrow[\text{}]{\text{finite-size sampling}} \mathbf{p}_{\mathbf{exp}}^{\text{est}}\ ,$$ 
which simply consists of experimental frequencies of occurances of particular outcomes. 

As a result, we will have some statistical noise in our estimator, which we can write as
$$
\mathbf{p}_{\mathbf{exp}}^{\text{est}}  = \mathbf{p}_{\mathbf{exp}} + \mathbf{s} \ ,
$$
where $\mathbf{s}$ is some vector of statistical deviations. 

Let us assume that we perform $n$-outcome measurement and gather $k$ samples (shots). Then the magnitude of those statistical deviations can be upper bound by
$$
D_{TV}\left(\mathbf{p}_{\mathbf{exp}}^{\text{est}} , \mathbf{p}_{\mathbf{exp}} \right) \leq \sqrt{\frac{\log{\left(2^n-2\right)}-\log{\text{Pr}_{wrong}}}{2k}} \equiv \epsilon \ .
$$
Bounds on statistical deviations are usually probabilitic, and in the above equation we choose parameter $\text{Pr}_{wrong}$ such that
$$
1-\text{Pr}_{wrong} = \text{Pr}\left(D_{TV}\left(\mathbf{p}_{\mathbf{exp}}^{\text{est}} , \mathbf{p}_{\mathbf{exp}} \right) \leq \epsilon\right) \ .
$$

#### Effects on mitigation
Now we want to determine how far (in TV distance) is our corrected estimated statistics vector $\Lambda^{-1}\mathbf{p}_{\mathbf{exp}}^{\text{est}}$ from ideal statistics $\mathbf{p_{ideal}}$. 
This distance can be upper bounded by

$$ D_{TV}\left(\Lambda^{-1} \mathbf{p}_{\mathbf{exp}}^{\text{est}}, \mathbf{p_{ideal}}\right) \leq \underbrace{||\Lambda^{-1}||_{1 \to 1} D_{op}(\mathbf{M}, \Lambda \mathbf{P})}_{\text{coherent noise}} + \underbrace{||\Lambda^{-1}||_{1 \to 1} \epsilon}_{\text{statistical noise}} =: \delta. $$

This sum consists of two parts. 
First qunatifies propagation of coherent errors under our correction and is the same as in previous subsection. 
The second term quantifies propagation of statistical noise. For more details see Ref. [0].

### Quasiprobability vectors
TODO: finish




### When is mitigation succesful?
TODO: finish
We propose a simple test to decide it. We say, that mitigation was as success if

$$ \delta + \alpha < D_{op}(M^{exp}, M^{ideal}) + \epsilon,$$

where $\delta$ was introduced in previous section, $\alpha$ describes the distance between raw quasiprobability vector obtained during mitigation scheme and its closest probability vector (note, that it can be 0, if mitigation returned probability vector), and $\epsilon$ is statistical error.

## Mitigating the errors using our module

In this section we will describe how to use our mitigation module. We will begin with showing general approach as to how to prepare the mitigator object and then, on several examples, we will show how to use it (on single and multi-qubit circuit results). 

### Performing Quantum Detector Tomography
Our error mitigation approach is based on the knowledge about the noise in the device's detector. Such knowledge can be obtained in procedure known as Quantum Detector Tomography (QDT). To perform QDT, one can follow the steps from our [QDT tutorial](https://github.com/fbm2718/QREM/blob/master/QDT_Tutorial.ipynb). 

In [1]:
import povmtools
import ancillary_functions as anf
import numpy as np

from qiskit import IBMQ, Aer, execute
from qiskit.providers.aer import noise

from quantum_tomography_qiskit import detector_tomography_circuits
from DetectorTomographyFitter import DetectorTomographyFitter
from QDTErrorMitigator import QDTErrorMitigator

# Choose qubit indices
QDT_qubit_index = [3]

# Select probe kets
QDT_probe_kets = povmtools.pauli_probe_eigenkets

# Generate circuits
QDT_circuits = detector_tomography_circuits(QDT_qubit_index, QDT_probe_kets)

# Get QDT circuits results
backend = Aer.get_backend('qasm_simulator')  #  Get backed
shots_number = 2000  # Define number of measurement repetitions
QDT_job = execute(QDT_circuits, backend=backend, shots=shots_number)
results = QDT_job.result()

# Get ml_povm_estimator using DTF and results
DTF = DetectorTomographyFitter()
ml_povm_estimator = DTF.get_maximum_likelihood_povm_estimator([results], QDT_probe_kets)

## Preparing mitigation

Now that we have the estimator of POVM, we can create QDTErrorMitigator object and prepare it.

In [2]:
# Creation and preparation of QDTErrorMitigator
mitigator = QDTErrorMitigator()
mitigator.prepare_mitigator(ml_povm_estimator)

With prepared mitigator object we gain access to several useful functionalities. For example, we can:
* Correct results of qiskit job by using apply_correction_to_qiskit_job(Results) method.
* Access error and correction matrices obtained from POVM given during preparation.

In order to properly analyse the results of correction procedure, one have to be aware that in some cases raw application of $\Lambda^{-1}$ to the results may yield quasiprobability (instead of probability) vectors. In such scenario our code finds closest probability vectors and returns them instead. Distances from raw quasiprobabilities to returned probabilities, can be accessed via distances_from_closest_probability_vector member of mitigator object.

### Error bounds calculation

With access to POVM and the error and correction matrices, we are able to calculate bounds on several errors. In particular, using povmtools module, we can calculate:

* statistical error bound (using get_statistical_error_bound method),
* coherent error bound (using gt_coherent_error_bound method),
* correction error bound (using get_correction_error_bound_from_data or get_correction_error_bound_from_parameters method).  

## Single qubit error mitigation scenario

In this section two examples of mitigation for single qubit will be shown. In order to show, that our mitigation scheme is efficient, we first need to create a noisy backend simulator. We start with required imports. 

In [3]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import execute
from qiskit import IBMQ, Aer
from qiskit.providers.aer.noise import NoiseModel
import pandas as pd
from pprint import pprint

import povmtools
from DetectorTomographyFitter import DetectorTomographyFitter
from quantum_tomography_qiskit import detector_tomography_circuits
from QDTErrorMitigator import QDTErrorMitigator

We use standard qiskit methods to create noisy backend simulator. For this tutorial we will create simulator of IBM's Burlington device which is usually quite noisy. Here the assumed model is classical, hece all errors in mitigation will be due to statistical noise.

In [4]:
#  What I want to have first is working noisy backend simulation. In order to do that, I will use qiskit noise model
# and download properties of selected backend.

# Build noise model from backend properties.
provider = IBMQ.load_account()
backend = provider.get_backend('ibmq_burlington')
noise_model = NoiseModel.from_backend(backend)

# Get coupling map from backend, why not.
coupling_map = backend.configuration().coupling_map

# Get basis gates from noise model.
basis_gates = noise_model.basis_gates

# Finally, get the simulator backend.
simulator_backend = Aer.get_backend('qasm_simulator')

With backend created, what I need to do next is calculating POVM that describes its measurements best. To do that, following our QDT tutorial, I use DetectorTomographyFitter object from our module. In order to do that, I need to create calibration circuits and obtain their results first.

In [5]:
# What I want to do now, is prepare POVM for simulated backend. According to our other notebook, I prepare
# circuits first.

qdt_qubit_index = [0]
qdt_probe_kets = povmtools.pauli_probe_eigenkets
qdt_calibration_circuits = detector_tomography_circuits(qdt_qubit_index, qdt_probe_kets)

# I then execute them on backend prepared earlier.
shots_number = 8192

# Perform a noisy simulation
result = execute(qdt_calibration_circuits, simulator_backend, coupling_map=coupling_map, basis_gates=basis_gates,
                 noise_model=noise_model, shots=shots_number)\
                 .result()

# Print counts.
for i in range(len(result.results)):
    counts_now = result.get_counts(i)
    frequencies_now = povmtools.counts_dict_to_frequencies_vector(counts_now)
    print(np.round(frequencies_now,3))

[0.951 0.049]
[0.047 0.953]
[0.498 0.502]
[0.499 0.501]
[0.499 0.501]
[0.496 0.504]


We note that it is highly preferable to use as high number of shots as possible to minimize statistical errors.  

Maximum likelihood POVM calculation is as easy as calling single method now.

In [6]:
# With circuits results I can now use our Detector Tomography Fitter to obtain maximum likelihood POVM estimator.
dtf = DetectorTomographyFitter()
ml_povm_estimator = dtf.get_maximum_likelihood_povm_estimator([result], qdt_probe_kets)

for m_i in ml_povm_estimator:
    nice_looking_m_i = pd.DataFrame(m_i)
    print(nice_looking_m_i)

                    0                   1
0  0.951083-0.000000j -0.000305-0.001404j
1 -0.000305+0.001404j  0.046678-0.000000j
                    0                   1
0  0.048917+0.000000j  0.000305+0.001404j
1  0.000305-0.001404j  0.953322+0.000000j


With POVM calculated, we can now create and prepare mitigator object.

In [7]:
# I can use obtained POVM to correct to prepare mitigation object.
mitigator = QDTErrorMitigator()
mitigator.prepare_mitigator(ml_povm_estimator)

After those preparations, we can now check how efficient our error mitigation approach is. Let's consider two simple scenarios.

### X gate circuit

In this case, we will first create a one qubit circuit (initially in |0><0| state) and we will apply X (not) operation to it. In ideal scenario we would expect all counts in state |1><1|. We begin with circuit creation.

In [8]:
# In order to check how efficient our mitigator is, we need to obtain some noisy data first.
# We will start with preparing simple experiment.

qr = QuantumRegister(1, 'qreg')
cr = ClassicalRegister(1, 'creg')
qc = QuantumCircuit(qr, cr)

qc.x(qr[0])
qc.measure(qr, cr);

Now we execute this circuit on our simulator and check the results.

In [9]:
result = execute(qc, simulator_backend, coupling_map=coupling_map, basis_gates=basis_gates,
                 noise_model=noise_model, shots=shots_number)\
                 .result()

for i in range(len(result.results)):
    counts_now = result.get_counts(i)
    frequencies_now = povmtools.counts_dict_to_frequencies_vector(counts_now)
    print(np.round(frequencies_now,3))

[0.042 0.958]


As we can see, noisy simulator returned some errors (|0><0| counts), as expected. Let's try to correct these results using our mitigator.

In [10]:
# Now let's correct them.
corrected_results = mitigator.apply_correction_to_qiskit_job(result)
print(np.round(corrected_results[0],3))

good format
[[0.]
 [1.]]


### H gate circuit

In this case, we will use H (Hadamard) gate, instead of X. Everything else will be exactly like in the first scenario. We begin with creating and executing a circuit and then printing raw results of the job. We expect to obtain equal number of |1> and |0> states conuts.

In [11]:
# Let's try another example.
qr2 = QuantumRegister(1, 'qreg2')
cr2 = ClassicalRegister(1, 'creg2')
qc2 = QuantumCircuit(qr2, cr2)

qc2.h(qr2[0])
qc2.measure(qr2, cr2)

result = execute(qc2, simulator_backend, coupling_map=coupling_map, basis_gates=basis_gates,
                 noise_model=noise_model, shots=shots_number)\
                 .result()

for i in range(len(result.results)):
    counts_now = result.get_counts(i)
    frequencies_now = povmtools.counts_dict_to_frequencies_vector(counts_now)
    print(np.round(frequencies_now,3))

[0.491 0.509]


We see that again have distribution which is not perfect. Let's try to apply error mitigation.

In [12]:
# Now let's correct them.
corrected_results = mitigator.apply_correction_to_qiskit_job(result)
print(np.round(corrected_results[0],3))

good format
[[0.492]
 [0.508]]


Once again, the results are better!

### Errors in mitigation
In the above benchmark circuits it was straightforward to assess the effectivness of mitigation - since we knew the theoretical distributions, we could simply compare the corrected statistics to this distribution.

In realistic scenarios, however, if one does not know what is the underlying ideal distribution, it is impossible to assess the success of mitigation. However, following procedure described in [0], we can heuristically assses if it is likely that mitigation succeded (see theoretical background of this tutorial). 

We start with calculating statistical error bound. We start with setting mistake probability (in theoretical background denoted as $\text{Pr}_{\text{wrong}}$). 

In [13]:
# We can check out if mitigation was success. In order to do that, we have to calculate error bounds.
# Let's assume (according to the notation form the main paper) that alpha=0.

statistical_error_mistake_probability = 0.01

Now we need counts formatted as list or array.

In [14]:
# We need counts as array. The outcomes are 0 or 1, so we can create them in straightforward way.
counts_dict = result.get_counts()
counts_list = [counts_dict['0'], counts_dict['1']]

Now we can use povmtools method to calculate statistical error bound.

In [15]:
# We calculate statistical error bound. Let's call it epsilon.
epsilon = povmtools.get_statistical_error_bound(counts_list, statistical_error_mistake_probability)
print('statistical errors:',epsilon)

statistical errors: 0.017982870414073163


That's, however, not enough. We'll also require correction error. Luckily, we have all the arguments necessary for its calculation using prepared povmtools method.

In [16]:
#get correction matrix
correction_matrix = mitigator.correction_matrix


#do not forget about possible term from unphysicality. 
alpha = mitigator.distances_from_closest_probability_vector[0]
print('unphysicality error:',alpha)



# We now need the correction error bound. Let's call it delta.
delta = povmtools.get_correction_error_bound_from_data_and_statistical_error(ml_povm_estimator,
                                                                             correction_matrix, 
                                                                             epsilon,
                                                                             alpha)


print('total mitigation error:',delta)

unphysicality error: 0
total mitigation error: 0.021520187615865282


Note that since we took a classical noise model from IBM's backend properties, the above error arises solely due to statistical fluctuations and is underestimated since it does not account for coherent errors.

Last thing required for determining mitigation success is operational distance between perfect measurement and our ml_povm_estimator. We calculate it, once again, using povmtools module function.

In [17]:
# We also need operational distance, between perfect detector and our POVM. We calculate it.
perfect_measurement = povmtools.computational_projectors(d=2) # For one qubit!
operational_distance = povmtools.operational_distance_POVMs(ml_povm_estimator, perfect_measurement)
print('errors without mitigation:',operational_distance)

errors without mitigation: 0.04893864029745742


And finally, we can check if our mitigation was likely to be a success!

In [18]:
# Now we can check if mitigation can be considered successfull
print(f'Mitigation successfull: {delta < operational_distance + epsilon}')

Mitigation successfull: True


## Multi Qubit error mitigation scenario

Our method can easily be expanded for multiple qubits. It's done analogically to the single qubit experiments. We start with preparing noisy backend, again. We can use the same code as in one qubit scenario.

In [19]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import execute
from qiskit import IBMQ, Aer
from qiskit.providers.aer.noise import NoiseModel

import povmtools
from DetectorTomographyFitter import DetectorTomographyFitter
from quantum_tomography_qiskit import detector_tomography_circuits
from QDTErrorMitigator import QDTErrorMitigator

#  What I want to have first is working noisy backend simulation. In order to do that, I will use qiskit noise model
# and download properties of selected backend.

# Build noise model from backend properties.
provider = IBMQ.load_account()
backend = provider.get_backend('ibmq_burlington')
noise_model = NoiseModel.from_backend(backend)

# Get coupling map from backend, why not.
coupling_map = backend.configuration().coupling_map

# Get basis gates from noise model.
basis_gates = noise_model.basis_gates

# Finally, get the simulator backend.
simulator_backend = Aer.get_backend('qasm_simulator')

ibmqfactory.load_account:WARNING:2020-04-14 20:29:59,119: Credentials are already in use. The existing account in the session will be replaced.


Now the POVM. This time we need higher dimensional one, as we are concerning multi qubit scenario. The code, however, doesn't change much. The only thing we need to do is modify qdt_qubit_indices list.

In [20]:
# What I want to do now, is prepare POVM for simulated backend. According to our other notebook, I prepare
# circuits first.

qdt_qubit_indices = [0, 1]
qdt_probe_kets = povmtools.pauli_probe_eigenkets
qdt_calibration_circuits = detector_tomography_circuits(qdt_qubit_indices, qdt_probe_kets)

# I then execute them on backend prepared earlier.
shots_number = 8192

# Perform a noisy simulation
result = execute(qdt_calibration_circuits, simulator_backend, coupling_map=coupling_map, basis_gates=basis_gates,
                 noise_model=noise_model, shots=shots_number) \
    .result()

# Print counts.
for i in range(len(result.results)):
    counts_now = result.get_counts(i)
    frequencies_now = povmtools.counts_dict_to_frequencies_vector(counts_now)
    print(np.round(frequencies_now,3))

[0.915 0.043 0.04  0.002]
[0.083 0.004 0.868 0.044]
[0.505 0.024 0.449 0.023]
[0.495 0.026 0.455 0.025]
[0.502 0.026 0.448 0.024]
[0.494 0.023 0.459 0.024]
[0.036 0.925 0.001 0.038]
[0.003 0.088 0.035 0.874]
[0.024 0.506 0.02  0.45 ]
[0.022 0.5   0.019 0.459]
[0.021 0.508 0.022 0.448]
[0.022 0.508 0.02  0.45 ]
[0.465 0.492 0.021 0.023]
[0.047 0.051 0.443 0.459]
[0.255 0.268 0.235 0.242]
[0.256 0.276 0.224 0.244]
[0.264 0.265 0.231 0.24 ]
[0.266 0.267 0.232 0.235]
[0.476 0.48  0.022 0.022]
[0.047 0.047 0.448 0.458]
[0.26  0.263 0.232 0.245]
[0.257 0.264 0.238 0.241]
[0.269 0.266 0.236 0.229]
[0.263 0.263 0.232 0.241]
[0.476 0.475 0.025 0.024]
[0.045 0.043 0.455 0.458]
[0.268 0.27  0.227 0.235]
[0.267 0.258 0.239 0.235]
[0.253 0.265 0.24  0.242]
[0.263 0.268 0.23  0.239]
[0.478 0.481 0.021 0.02 ]
[0.046 0.044 0.444 0.466]
[0.252 0.277 0.234 0.236]
[0.258 0.265 0.242 0.234]
[0.254 0.265 0.238 0.244]
[0.256 0.268 0.236 0.24 ]


Now, we can calculate the POVM estimator.

In [21]:
# With circuits results I can now use our Detector Tomography Fitter to obtain maximum likelihood POVM estimator.
dtf = DetectorTomographyFitter()
ml_povm_estimator = dtf.get_maximum_likelihood_povm_estimator([result], qdt_probe_kets)

for m_i in ml_povm_estimator:
    nice_looking_m_i = pd.DataFrame(m_i)
    print(nice_looking_m_i,'\n')

                    0                   1                   2  \
0  0.911396-0.000000j  0.002777+0.000452j -0.003500-0.002462j   
1  0.002777-0.000452j  0.087679-0.000000j -0.003046-0.003397j   
2 -0.003500+0.002462j -0.003046+0.003397j  0.038715+0.000000j   
3  0.000684-0.000340j  0.000214+0.000448j  0.000510-0.000517j   

                    3  
0  0.000684+0.000340j  
1  0.000214-0.000448j  
2  0.000510+0.000517j  
3  0.003346+0.000000j   

                    0                   1                   2  \
0  0.041592+0.000000j -0.001744+0.000845j -0.000711-0.001183j   
1 -0.001744-0.000845j  0.862278-0.000000j  0.006242-0.000028j   
2 -0.000711+0.001183j  0.006242+0.000028j  0.001315-0.000000j   
3  0.002393-0.001926j -0.002893+0.000536j -0.000124+0.001468j   

                    3  
0  0.002393+0.001926j  
1 -0.002893-0.000536j  
2 -0.000124-0.001468j  
3  0.037545+0.000000j   

                    0                   1                   2  \
0  0.045067-0.000000j -0.000848-0.00107

And with POVM estimator, we can prepare mitigator object.

In [22]:
# I can use obtained POVM to correct to prepare mitigation object.
mitigator = QDTErrorMitigator()
mitigator.prepare_mitigator(ml_povm_estimator)

Again, let's check how the mitigation work on several circuits.

### Hadamards circuit

We begin with circuit applying Hadamard gates on both qubits. Let's prepare such circuit.

In [23]:
# In order to check how efficient our mitigator is, we need to obtain some noisy data first.
# We will start with preparing simple experiment.

qr = QuantumRegister(2, 'qreg')
cr = ClassicalRegister(2, 'creg')
qc = QuantumCircuit(qr, cr)

qc.h(qr[0])
qc.h(qr[1])
qc.measure(qr, cr);

We then execute this circuit and print the results.

In [24]:
result = execute(qc, simulator_backend, coupling_map=coupling_map, basis_gates=basis_gates,
                 noise_model=noise_model, shots=shots_number) \
    .result()

for i in range(len(result.results)):
    counts_now = result.get_counts(i)
    frequencies_now = povmtools.counts_dict_to_frequencies_vector(counts_now)
    print(frequencies_now)

[0.267822265625, 0.2626953125, 0.2337646484375, 0.2357177734375]


Now we can correct them.

In [25]:
# Now let's correct them.
corrected_results = mitigator.apply_correction_to_qiskit_job(result)
print(corrected_results[0])

good format
[[0.25861098]
 [0.24791903]
 [0.24754082]
 [0.24592917]]


One can clarly see, that the results are better. 

Now let's it try with some multi-qubit gates.

### CNOT Circuit

This time we will use a CNOT gate. First we will prepare a qubit in state |1> and then use it as a control to negate the other qubit. We expect all counts to be in state |11>. The circuit can be codded as below.

In [26]:
# Let's try another example.
qr2 = QuantumRegister(2, 'qreg2')
cr2 = ClassicalRegister(2, 'creg2')
qc2 = QuantumCircuit(qr2, cr2)

qc2.x(qr2[0])
qc2.cx(qr2[0], qr2[1])
qc2.measure(qr2, cr2)

Executing this circuits yields following results:

In [27]:
result = execute(qc2, simulator_backend, coupling_map=coupling_map, basis_gates=basis_gates,
                 noise_model=noise_model, shots=shots_number) \
    .result()

for i in range(len(result.results)):
    counts_now = result.get_counts(i)
    frequencies_now = povmtools.counts_dict_to_frequencies_vector(counts_now)
    print(frequencies_now)

[0.0045166015625, 0.09423828125, 0.0411376953125, 0.860107421875]


As expected, we can see some erroneous results. Let's try to mitigate it.

In [28]:
# Now let's correct them.
corrected_results = mitigator.apply_correction_to_qiskit_job(result)
print(np.round(corrected_results[0],3))

good format
[[0.001]
 [0.007]
 [0.005]
 [0.988]]


Easily enough, the results are clearly better. Let's now combine Hadamard and CNOT gate.

### Hadamard + CNOT circuit

In this scenario, we will first prepare first qubit in superposition of states |0> and |1>. We will then, again, use it as a control qubit to negate the second one. We will expect equal number of counts in |00> and |11> states. The circuit can be prepared like below.

In [29]:
# Final example!
qr3 = QuantumRegister(2, 'qreg2')
cr3 = ClassicalRegister(2, 'creg2')
qc3 = QuantumCircuit(qr3, cr3)

qc3.h(qr3[0])
qc3.cx(qr3[0], qr2[1])
qc3.measure(qr3, cr3)

We now execute it and print the results.

In [30]:
result = execute(qc3, simulator_backend, coupling_map=coupling_map, basis_gates=basis_gates,
                 noise_model=noise_model, shots=shots_number) \
    .result()

for i in range(len(result.results)):
    counts_now = result.get_counts(i)
    frequencies_now = povmtools.counts_dict_to_frequencies_vector(counts_now)
    print(frequencies_now)

[0.45263671875, 0.06982421875, 0.041259765625, 0.436279296875]


There's some room for improvement. Let's apply the mitigation.

In [31]:
# Now let's correct them.
corrected_results = mitigator.apply_correction_to_qiskit_job(result)
print(np.round(corrected_results[0],3))

good format
[[0.494]
 [0.003]
 [0.002]
 [0.5  ]]


Once again, the results are clearly better.

We can, as in single-qubit example, check if our criterion for assesing mitigation success works in this case as well.

In [32]:
# We need counts as array. The outcomes are 0 or 1, so we can create them in straightforward way.
counts_dict = result.get_counts()
counts_list = np.array(povmtools.counts_dict_to_frequencies_vector(counts_dict))*shots_number


# We calculate statistical error bound. Let's call it epsilon.
epsilon = povmtools.get_statistical_error_bound(counts_list, statistical_error_mistake_probability)
print('statistical errors:',epsilon)



#get correction matrix
correction_matrix = mitigator.correction_matrix


#do not forget about possible term from unphysicality. 
alpha = mitigator.distances_from_closest_probability_vector[0]
print('unphysicality error:',alpha)



# We now need the correction error bound. Let's call it delta.
delta = povmtools.get_correction_error_bound_from_data_and_statistical_error(ml_povm_estimator,
                                                                             correction_matrix, 
                                                                             epsilon,
                                                                             alpha)


print('total mitigation error:',delta)

statistical errors: 0.021027423958378727
unphysicality error: 0
total mitigation error: 0.04079362488580693


Recall that since we took a classical noise model from IBM's backend properties, the above error arises solely due to statistical fluctuations and is underestimated since it does not account for coherent errors. Here errors are assumed to be uncorellated, which underestimates their magnitude.


Note that mitigation error is higher than in case of single-qubit experiments. This is due to the fact that sampling complexity is higher for 4-dimensional probability distributions. However, we expect that also errors without mitigation increase:

In [33]:
# We need operational distance between perfect detector and our POVM. We calculate it.
perfect_measurement = povmtools.computational_projectors(d=4) # For two qubits
operational_distance = povmtools.operational_distance_POVMs(ml_povm_estimator, perfect_measurement)
print('errors without mitigation:',operational_distance)

# Now we can check if mitigation can be considered succesfull
print(f'Mitigation successfull: {delta < operational_distance + epsilon}')

errors without mitigation: 0.13807070090100917
Mitigation successfull: True


As a final remark one should be aware that the results of the mitigation and its success in particular, might depend on quantum detector tomography method used during POVM calculation. In our work we used reconstruction algorithm from [1] with overcomplete Pauli basis as probe states. For more information see [0].

# References

[0] Filip B. Maciejewski, Zoltán Zimborás, Michał Oszmaniec, *Mitigation of readout noise in near-term quantum devices by classical post-processing based on detector tomography*, arxiv preprint, https://arxiv.org/abs/1907.08518 (2019)

[1] Z. Hradil, J. Řeháček, J. Fiurášek, and M. Ježek, “3 maximum-likelihood methods in quantum mechanics,” in Quantum
State Estimation, edited by M. Paris and J. Řeháček (Springer Berlin Heidelberg, Berlin, Heidelberg, 2004) pp. 59–112.
  